/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.Common;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace BWA.bigWebDesk.DAL
{

	#region Schema

	public class DeploymentLoggerUserSchema : NCI.EasyObjects.Schema
	{
		private static ArrayList _entries;
		public static SchemaItem ID = new SchemaItem("ID", DbType.Int32, true, false, false, true, false, false);
		public static SchemaItem LoginID = new SchemaItem("LoginID", DbType.Int32, false, false, false, false, true, false);
		public static SchemaItem DLUserID = new SchemaItem("DLUserID", DbType.Int32, false, false, false, false, false, false);

		public override ArrayList SchemaEntries
		{
			get
			{
				if (_entries == null )
				{
					_entries = new ArrayList();
					_entries.Add(DeploymentLoggerUserSchema.ID);
					_entries.Add(DeploymentLoggerUserSchema.LoginID);
					_entries.Add(DeploymentLoggerUserSchema.DLUserID);
				}
				return _entries;
			}
		}
	}
	#endregion

	public abstract class DeploymentLoggerUser : EasyObject
	{

		public DeploymentLoggerUser()
		{
			DeploymentLoggerUserSchema _schema = new DeploymentLoggerUserSchema();
			this.SchemaEntries = _schema.SchemaEntries;
			this.SchemaGlobal = "dbo";
		}
		
		public override void FlushData() 	 
		{ 	 
			this._whereClause = null; 	 
			this._aggregateClause = null; 	 
			base.FlushData(); 	 
		}
			   
		/// <summary>
		/// Loads the business object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="ID"></param>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadByPrimaryKey(int ID)
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					ListDictionary parameters = new ListDictionary();

					// Add in parameters
					parameters.Add(DeploymentLoggerUserSchema.ID.FieldName, ID);

					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "GetDeploymentLoggerUser", parameters, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.ID.Value = ID;
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}
	
		/// <summary>
		/// Loads all records from the table.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadAll()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "GetAllDeploymentLoggerUser", null, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		/// <summary>
		/// Adds a new record to the internal table.
		/// </summary>
		public override void AddNew()
		{
			base.AddNew();
		}

		protected override DbCommand GetInsertCommand(CommandType commandType)
		{	
			DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "AddDeploymentLoggerUser";
					dbCommand = db.GetStoredProcCommand(sqlCommand);

					db.AddParameter(dbCommand, "ID", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "ID", DataRowVersion.Default, Convert.DBNull);
					CreateParameters(db, dbCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddInsertColumn(item);
						}
					}
					dbCommand = this.Query.GetInsertCommandWrapper();

					dbCommand.Parameters.Clear();
					CreateParameters(db, dbCommand);
					db.AddParameter(dbCommand, "ID", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "ID", DataRowVersion.Default, Convert.DBNull);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DbCommand GetUpdateCommand(CommandType commandType)
		{
            DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "UpdateDeploymentLoggerUser";
					dbCommand = db.GetStoredProcCommand(sqlCommand);

					db.AddInParameter(dbCommand, "ID", DbType.Int32, "ID", DataRowVersion.Current);
					CreateParameters(db, dbCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddUpdateColumn(item);
						}
					}

					this.Where.WhereClauseReset();
					this.Where.ID.Operator = WhereParameter.Operand.Equal;
					dbCommand = this.Query.GetUpdateCommandWrapper();

					dbCommand.Parameters.Clear();
					CreateParameters(db, dbCommand);
					db.AddInParameter(dbCommand, "ID", DbType.Int32, "ID", DataRowVersion.Current);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DbCommand GetDeleteCommand(CommandType commandType)
		{
            DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "DeleteDeploymentLoggerUser";
					dbCommand = db.GetStoredProcCommand(sqlCommand);
					db.AddInParameter(dbCommand, "ID", DbType.Int32, "ID", DataRowVersion.Current);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.ID.Operator = WhereParameter.Operand.Equal;
					dbCommand = this.Query.GetDeleteCommandWrapper();

					dbCommand.Parameters.Clear();
					db.AddInParameter(dbCommand, "ID", DbType.Int32, "ID", DataRowVersion.Current);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		private void CreateParameters(Database db, DbCommand dbCommand)
		{
			db.AddInParameter(dbCommand, "LoginID", DbType.Int32, "LoginID", DataRowVersion.Current);
			db.AddInParameter(dbCommand, "DLUserID", DbType.Int32, "DLUserID", DataRowVersion.Current);
		}
		
		#region Properties
		public virtual int ID
		{
			get
			{
				return this.GetInteger(DeploymentLoggerUserSchema.ID.FieldName);
	    	}
			set
			{
				this.SetInteger(DeploymentLoggerUserSchema.ID.FieldName, value);
			}
		}
		public virtual int LoginID
		{
			get
			{
				return this.GetInteger(DeploymentLoggerUserSchema.LoginID.FieldName);
	    	}
			set
			{
				this.SetInteger(DeploymentLoggerUserSchema.LoginID.FieldName, value);
			}
		}
		public virtual int DLUserID
		{
			get
			{
				return this.GetInteger(DeploymentLoggerUserSchema.DLUserID.FieldName);
	    	}
			set
			{
				this.SetInteger(DeploymentLoggerUserSchema.DLUserID.FieldName, value);
			}
		}

		public override string TableName
		{
			get { return "DeploymentLoggerUser"; }
		}
		
		#endregion		
		
		#region String Properties
	
		public virtual string s_ID
	    {
			get
	        {
				return this.IsColumnNull(DeploymentLoggerUserSchema.ID.FieldName) ? string.Empty : base.GetIntegerAsString(DeploymentLoggerUserSchema.ID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(DeploymentLoggerUserSchema.ID.FieldName);
				else
					this.ID = base.SetIntegerAsString(DeploymentLoggerUserSchema.ID.FieldName, value);
			}
		}

		public virtual string s_LoginID
	    {
			get
	        {
				return this.IsColumnNull(DeploymentLoggerUserSchema.LoginID.FieldName) ? string.Empty : base.GetIntegerAsString(DeploymentLoggerUserSchema.LoginID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(DeploymentLoggerUserSchema.LoginID.FieldName);
				else
					this.LoginID = base.SetIntegerAsString(DeploymentLoggerUserSchema.LoginID.FieldName, value);
			}
		}

		public virtual string s_DLUserID
	    {
			get
	        {
				return this.IsColumnNull(DeploymentLoggerUserSchema.DLUserID.FieldName) ? string.Empty : base.GetIntegerAsString(DeploymentLoggerUserSchema.DLUserID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(DeploymentLoggerUserSchema.DLUserID.FieldName);
				else
					this.DLUserID = base.SetIntegerAsString(DeploymentLoggerUserSchema.DLUserID.FieldName, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ID
				{
					get
					{
							WhereParameter wp = new WhereParameter(DeploymentLoggerUserSchema.ID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter LoginID
				{
					get
					{
							WhereParameter wp = new WhereParameter(DeploymentLoggerUserSchema.LoginID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter DLUserID
				{
					get
					{
							WhereParameter wp = new WhereParameter(DeploymentLoggerUserSchema.DLUserID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public WhereParameter LoginID
		    {
				get
		        {
					if(_LoginID_W == null)
	        	    {
						_LoginID_W = TearOff.LoginID;
					}
					return _LoginID_W;
				}
			}

			public WhereParameter DLUserID
		    {
				get
		        {
					if(_DLUserID_W == null)
	        	    {
						_DLUserID_W = TearOff.DLUserID;
					}
					return _DLUserID_W;
				}
			}

			private WhereParameter _ID_W = null;
			private WhereParameter _LoginID_W = null;
			private WhereParameter _DLUserID_W = null;

			public void WhereClauseReset()
			{
				_ID_W = null;
				_LoginID_W = null;
				_DLUserID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private EasyObject _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(DeploymentLoggerUserSchema.ID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter LoginID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(DeploymentLoggerUserSchema.LoginID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter DLUserID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(DeploymentLoggerUserSchema.DLUserID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public AggregateParameter LoginID
		    {
				get
		        {
					if(_LoginID_W == null)
	        	    {
						_LoginID_W = TearOff.LoginID;
					}
					return _LoginID_W;
				}
			}

			public AggregateParameter DLUserID
		    {
				get
		        {
					if(_DLUserID_W == null)
	        	    {
						_DLUserID_W = TearOff.DLUserID;
					}
					return _DLUserID_W;
				}
			}

			private AggregateParameter _ID_W = null;
			private AggregateParameter _LoginID_W = null;
			private AggregateParameter _DLUserID_W = null;

			public void AggregateClauseReset()
			{
				_ID_W = null;
				_LoginID_W = null;
				_DLUserID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private EasyObject _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	}
}
