/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.Common;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace BWA.bigWebDesk.DAL
{

	#region Schema

	public class DeploymentLoggerSchema : NCI.EasyObjects.Schema
	{
		private static ArrayList _entries;
		public static SchemaItem ID = new SchemaItem("ID", DbType.Int32, true, false, false, false, false, false);
		public static SchemaItem CompanyID = new SchemaItem("companyID", DbType.Int32, false, false, false, false, true, false);
		public static SchemaItem DLOrganizationID = new SchemaItem("DLOrganizationID", DbType.Int32, false, false, false, false, false, false);
		public static SchemaItem DLDepartmentID = new SchemaItem("DLDepartmentID", DbType.Int32, false, false, false, false, false, false);
		public static SchemaItem Enabled = new SchemaItem("Enabled", DbType.Boolean, false, false, false, false, false, true);

		public override ArrayList SchemaEntries
		{
			get
			{
				if (_entries == null )
				{
					_entries = new ArrayList();
					_entries.Add(DeploymentLoggerSchema.ID);
					_entries.Add(DeploymentLoggerSchema.CompanyID);
					_entries.Add(DeploymentLoggerSchema.DLOrganizationID);
					_entries.Add(DeploymentLoggerSchema.DLDepartmentID);
					_entries.Add(DeploymentLoggerSchema.Enabled);
				}
				return _entries;
			}
		}
	}
	#endregion

	public abstract class DeploymentLogger : EasyObject
	{

		public DeploymentLogger()
		{
			DeploymentLoggerSchema _schema = new DeploymentLoggerSchema();
			this.SchemaEntries = _schema.SchemaEntries;
			this.SchemaGlobal = "dbo";
		}
		
		public override void FlushData() 	 
		{ 	 
			this._whereClause = null; 	 
			this._aggregateClause = null; 	 
			base.FlushData(); 	 
		}
			   
		/// <summary>
		/// Loads the business object with info from the database, based on the requested primary key.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadByPrimaryKey()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					ListDictionary parameters = new ListDictionary();

					// Add in parameters

					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "GetDeploymentLogger", parameters, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}
	
		/// <summary>
		/// Loads all records from the table.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadAll()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "GetAllDeploymentLogger", null, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		/// <summary>
		/// Adds a new record to the internal table.
		/// </summary>
		public override void AddNew()
		{
			base.AddNew();
		}

		protected override DbCommand GetInsertCommand(CommandType commandType)
		{	
			DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "AddDeploymentLogger";
					dbCommand = db.GetStoredProcCommand(sqlCommand);

					CreateParameters(db, dbCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddInsertColumn(item);
						}
					}
					dbCommand = this.Query.GetInsertCommandWrapper();

					dbCommand.Parameters.Clear();
					CreateParameters(db, dbCommand);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DbCommand GetUpdateCommand(CommandType commandType)
		{
            DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "UpdateDeploymentLogger";
					dbCommand = db.GetStoredProcCommand(sqlCommand);

					CreateParameters(db, dbCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddUpdateColumn(item);
						}
					}

					this.Where.WhereClauseReset();
					dbCommand = this.Query.GetUpdateCommandWrapper();

					dbCommand.Parameters.Clear();
					CreateParameters(db, dbCommand);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DbCommand GetDeleteCommand(CommandType commandType)
		{
            DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "DeleteDeploymentLogger";
					dbCommand = db.GetStoredProcCommand(sqlCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					dbCommand = this.Query.GetDeleteCommandWrapper();

					dbCommand.Parameters.Clear();
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		private void CreateParameters(Database db, DbCommand dbCommand)
		{
			db.AddInParameter(dbCommand, "companyID", DbType.Int32, "companyID", DataRowVersion.Current);
			db.AddInParameter(dbCommand, "DLOrganizationID", DbType.Int32, "DLOrganizationID", DataRowVersion.Current);
			db.AddInParameter(dbCommand, "DLDepartmentID", DbType.Int32, "DLDepartmentID", DataRowVersion.Current);
			db.AddInParameter(dbCommand, "Enabled", DbType.Boolean, "Enabled", DataRowVersion.Current);
		}
		
		#region Properties
		public virtual int ID
		{
			get
			{
				return this.GetInteger(DeploymentLoggerSchema.ID.FieldName);
	    	}
			set
			{
				this.SetInteger(DeploymentLoggerSchema.ID.FieldName, value);
			}
		}
		public virtual int CompanyID
		{
			get
			{
				return this.GetInteger(DeploymentLoggerSchema.CompanyID.FieldName);
	    	}
			set
			{
				this.SetInteger(DeploymentLoggerSchema.CompanyID.FieldName, value);
			}
		}
		public virtual int DLOrganizationID
		{
			get
			{
				return this.GetInteger(DeploymentLoggerSchema.DLOrganizationID.FieldName);
	    	}
			set
			{
				this.SetInteger(DeploymentLoggerSchema.DLOrganizationID.FieldName, value);
			}
		}
		public virtual int DLDepartmentID
		{
			get
			{
				return this.GetInteger(DeploymentLoggerSchema.DLDepartmentID.FieldName);
	    	}
			set
			{
				this.SetInteger(DeploymentLoggerSchema.DLDepartmentID.FieldName, value);
			}
		}
		public virtual bool Enabled
		{
			get
			{
				return this.GetBoolean(DeploymentLoggerSchema.Enabled.FieldName);
	    	}
			set
			{
				this.SetBoolean(DeploymentLoggerSchema.Enabled.FieldName, value);
			}
		}

		public override string TableName
		{
			get { return "DeploymentLogger"; }
		}
		
		#endregion		
		
		#region String Properties
	
		public virtual string s_ID
	    {
			get
	        {
				return this.IsColumnNull(DeploymentLoggerSchema.ID.FieldName) ? string.Empty : base.GetIntegerAsString(DeploymentLoggerSchema.ID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(DeploymentLoggerSchema.ID.FieldName);
				else
					this.ID = base.SetIntegerAsString(DeploymentLoggerSchema.ID.FieldName, value);
			}
		}

		public virtual string s_CompanyID
	    {
			get
	        {
				return this.IsColumnNull(DeploymentLoggerSchema.CompanyID.FieldName) ? string.Empty : base.GetIntegerAsString(DeploymentLoggerSchema.CompanyID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(DeploymentLoggerSchema.CompanyID.FieldName);
				else
					this.CompanyID = base.SetIntegerAsString(DeploymentLoggerSchema.CompanyID.FieldName, value);
			}
		}

		public virtual string s_DLOrganizationID
	    {
			get
	        {
				return this.IsColumnNull(DeploymentLoggerSchema.DLOrganizationID.FieldName) ? string.Empty : base.GetIntegerAsString(DeploymentLoggerSchema.DLOrganizationID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(DeploymentLoggerSchema.DLOrganizationID.FieldName);
				else
					this.DLOrganizationID = base.SetIntegerAsString(DeploymentLoggerSchema.DLOrganizationID.FieldName, value);
			}
		}

		public virtual string s_DLDepartmentID
	    {
			get
	        {
				return this.IsColumnNull(DeploymentLoggerSchema.DLDepartmentID.FieldName) ? string.Empty : base.GetIntegerAsString(DeploymentLoggerSchema.DLDepartmentID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(DeploymentLoggerSchema.DLDepartmentID.FieldName);
				else
					this.DLDepartmentID = base.SetIntegerAsString(DeploymentLoggerSchema.DLDepartmentID.FieldName, value);
			}
		}

		public virtual string s_Enabled
	    {
			get
	        {
				return this.IsColumnNull(DeploymentLoggerSchema.Enabled.FieldName) ? string.Empty : base.GetBooleanAsString(DeploymentLoggerSchema.Enabled.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(DeploymentLoggerSchema.Enabled.FieldName);
				else
					this.Enabled = base.SetBooleanAsString(DeploymentLoggerSchema.Enabled.FieldName, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ID
				{
					get
					{
							WhereParameter wp = new WhereParameter(DeploymentLoggerSchema.ID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter CompanyID
				{
					get
					{
							WhereParameter wp = new WhereParameter(DeploymentLoggerSchema.CompanyID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter DLOrganizationID
				{
					get
					{
							WhereParameter wp = new WhereParameter(DeploymentLoggerSchema.DLOrganizationID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter DLDepartmentID
				{
					get
					{
							WhereParameter wp = new WhereParameter(DeploymentLoggerSchema.DLDepartmentID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter Enabled
				{
					get
					{
							WhereParameter wp = new WhereParameter(DeploymentLoggerSchema.Enabled);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public WhereParameter CompanyID
		    {
				get
		        {
					if(_CompanyID_W == null)
	        	    {
						_CompanyID_W = TearOff.CompanyID;
					}
					return _CompanyID_W;
				}
			}

			public WhereParameter DLOrganizationID
		    {
				get
		        {
					if(_DLOrganizationID_W == null)
	        	    {
						_DLOrganizationID_W = TearOff.DLOrganizationID;
					}
					return _DLOrganizationID_W;
				}
			}

			public WhereParameter DLDepartmentID
		    {
				get
		        {
					if(_DLDepartmentID_W == null)
	        	    {
						_DLDepartmentID_W = TearOff.DLDepartmentID;
					}
					return _DLDepartmentID_W;
				}
			}

			public WhereParameter Enabled
		    {
				get
		        {
					if(_Enabled_W == null)
	        	    {
						_Enabled_W = TearOff.Enabled;
					}
					return _Enabled_W;
				}
			}

			private WhereParameter _ID_W = null;
			private WhereParameter _CompanyID_W = null;
			private WhereParameter _DLOrganizationID_W = null;
			private WhereParameter _DLDepartmentID_W = null;
			private WhereParameter _Enabled_W = null;

			public void WhereClauseReset()
			{
				_ID_W = null;
				_CompanyID_W = null;
				_DLOrganizationID_W = null;
				_DLDepartmentID_W = null;
				_Enabled_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private EasyObject _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(DeploymentLoggerSchema.ID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter CompanyID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(DeploymentLoggerSchema.CompanyID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter DLOrganizationID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(DeploymentLoggerSchema.DLOrganizationID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter DLDepartmentID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(DeploymentLoggerSchema.DLDepartmentID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter Enabled
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(DeploymentLoggerSchema.Enabled);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public AggregateParameter CompanyID
		    {
				get
		        {
					if(_CompanyID_W == null)
	        	    {
						_CompanyID_W = TearOff.CompanyID;
					}
					return _CompanyID_W;
				}
			}

			public AggregateParameter DLOrganizationID
		    {
				get
		        {
					if(_DLOrganizationID_W == null)
	        	    {
						_DLOrganizationID_W = TearOff.DLOrganizationID;
					}
					return _DLOrganizationID_W;
				}
			}

			public AggregateParameter DLDepartmentID
		    {
				get
		        {
					if(_DLDepartmentID_W == null)
	        	    {
						_DLDepartmentID_W = TearOff.DLDepartmentID;
					}
					return _DLDepartmentID_W;
				}
			}

			public AggregateParameter Enabled
		    {
				get
		        {
					if(_Enabled_W == null)
	        	    {
						_Enabled_W = TearOff.Enabled;
					}
					return _Enabled_W;
				}
			}

			private AggregateParameter _ID_W = null;
			private AggregateParameter _CompanyID_W = null;
			private AggregateParameter _DLOrganizationID_W = null;
			private AggregateParameter _DLDepartmentID_W = null;
			private AggregateParameter _Enabled_W = null;

			public void AggregateClauseReset()
			{
				_ID_W = null;
				_CompanyID_W = null;
				_DLOrganizationID_W = null;
				_DLDepartmentID_W = null;
				_Enabled_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private EasyObject _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	}
}
