/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.Common;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace BWA.bigWebDesk.DAL
{

	#region Schema

	public class RoutingOrderSchema : NCI.EasyObjects.Schema
	{
		private static ArrayList _entries;
		public static SchemaItem DId = new SchemaItem("DId", DbType.Int32, false, false, false, false, false, false);
		public static SchemaItem TintOrder = new SchemaItem("tintOrder", DbType.Byte, false, false, false, false, false, false);
		public static SchemaItem TintRoute = new SchemaItem("tintRoute", DbType.Byte, false, false, false, false, false, false);

		public override ArrayList SchemaEntries
		{
			get
			{
				if (_entries == null )
				{
					_entries = new ArrayList();
					_entries.Add(RoutingOrderSchema.DId);
					_entries.Add(RoutingOrderSchema.TintOrder);
					_entries.Add(RoutingOrderSchema.TintRoute);
				}
				return _entries;
			}
		}
	}
	#endregion

	public abstract class RoutingOrder : EasyObject
	{

		public RoutingOrder()
		{
			RoutingOrderSchema _schema = new RoutingOrderSchema();
			this.SchemaEntries = _schema.SchemaEntries;
			this.SchemaGlobal = "dbo";
		}
		
		public override void FlushData() 	 
		{ 	 
			this._whereClause = null; 	 
			this._aggregateClause = null; 	 
			base.FlushData(); 	 
		}
			   
		/// <summary>
		/// Loads the business object with info from the database, based on the requested primary key.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadByPrimaryKey()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					ListDictionary parameters = new ListDictionary();

					// Add in parameters

					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "GetRoutingOrder", parameters, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}
	
		/// <summary>
		/// Loads all records from the table.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadAll()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "GetAllRoutingOrder", null, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		/// <summary>
		/// Adds a new record to the internal table.
		/// </summary>
		public override void AddNew()
		{
			base.AddNew();
		}

		protected override DbCommand GetInsertCommand(CommandType commandType)
		{	
			DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "AddRoutingOrder";
					dbCommand = db.GetStoredProcCommand(sqlCommand);

					CreateParameters(db, dbCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddInsertColumn(item);
						}
					}
					dbCommand = this.Query.GetInsertCommandWrapper();

					dbCommand.Parameters.Clear();
					CreateParameters(db, dbCommand);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DbCommand GetUpdateCommand(CommandType commandType)
		{
            DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "UpdateRoutingOrder";
					dbCommand = db.GetStoredProcCommand(sqlCommand);

					CreateParameters(db, dbCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddUpdateColumn(item);
						}
					}

					this.Where.WhereClauseReset();
					dbCommand = this.Query.GetUpdateCommandWrapper();

					dbCommand.Parameters.Clear();
					CreateParameters(db, dbCommand);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DbCommand GetDeleteCommand(CommandType commandType)
		{
            DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "DeleteRoutingOrder";
					dbCommand = db.GetStoredProcCommand(sqlCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					dbCommand = this.Query.GetDeleteCommandWrapper();

					dbCommand.Parameters.Clear();
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		private void CreateParameters(Database db, DbCommand dbCommand)
		{
			db.AddInParameter(dbCommand, "DId", DbType.Int32, "DId", DataRowVersion.Current);
			db.AddInParameter(dbCommand, "tintOrder", DbType.Byte, "tintOrder", DataRowVersion.Current);
			db.AddInParameter(dbCommand, "tintRoute", DbType.Byte, "tintRoute", DataRowVersion.Current);
		}
		
		#region Properties
		public virtual int DId
		{
			get
			{
				return this.GetInteger(RoutingOrderSchema.DId.FieldName);
	    	}
			set
			{
				this.SetInteger(RoutingOrderSchema.DId.FieldName, value);
			}
		}
		public virtual byte TintOrder
		{
			get
			{
				return this.GetByte(RoutingOrderSchema.TintOrder.FieldName);
	    	}
			set
			{
				this.SetByte(RoutingOrderSchema.TintOrder.FieldName, value);
			}
		}
		public virtual byte TintRoute
		{
			get
			{
				return this.GetByte(RoutingOrderSchema.TintRoute.FieldName);
	    	}
			set
			{
				this.SetByte(RoutingOrderSchema.TintRoute.FieldName, value);
			}
		}

		public override string TableName
		{
			get { return "RoutingOrder"; }
		}
		
		#endregion		
		
		#region String Properties
	
		public virtual string s_DId
	    {
			get
	        {
				return this.IsColumnNull(RoutingOrderSchema.DId.FieldName) ? string.Empty : base.GetIntegerAsString(RoutingOrderSchema.DId.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(RoutingOrderSchema.DId.FieldName);
				else
					this.DId = base.SetIntegerAsString(RoutingOrderSchema.DId.FieldName, value);
			}
		}

		public virtual string s_TintOrder
	    {
			get
	        {
				return this.IsColumnNull(RoutingOrderSchema.TintOrder.FieldName) ? string.Empty : base.GetByteAsString(RoutingOrderSchema.TintOrder.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(RoutingOrderSchema.TintOrder.FieldName);
				else
					this.TintOrder = base.SetByteAsString(RoutingOrderSchema.TintOrder.FieldName, value);
			}
		}

		public virtual string s_TintRoute
	    {
			get
	        {
				return this.IsColumnNull(RoutingOrderSchema.TintRoute.FieldName) ? string.Empty : base.GetByteAsString(RoutingOrderSchema.TintRoute.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(RoutingOrderSchema.TintRoute.FieldName);
				else
					this.TintRoute = base.SetByteAsString(RoutingOrderSchema.TintRoute.FieldName, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter DId
				{
					get
					{
							WhereParameter wp = new WhereParameter(RoutingOrderSchema.DId);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter TintOrder
				{
					get
					{
							WhereParameter wp = new WhereParameter(RoutingOrderSchema.TintOrder);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter TintRoute
				{
					get
					{
							WhereParameter wp = new WhereParameter(RoutingOrderSchema.TintRoute);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter DId
		    {
				get
		        {
					if(_DId_W == null)
	        	    {
						_DId_W = TearOff.DId;
					}
					return _DId_W;
				}
			}

			public WhereParameter TintOrder
		    {
				get
		        {
					if(_TintOrder_W == null)
	        	    {
						_TintOrder_W = TearOff.TintOrder;
					}
					return _TintOrder_W;
				}
			}

			public WhereParameter TintRoute
		    {
				get
		        {
					if(_TintRoute_W == null)
	        	    {
						_TintRoute_W = TearOff.TintRoute;
					}
					return _TintRoute_W;
				}
			}

			private WhereParameter _DId_W = null;
			private WhereParameter _TintOrder_W = null;
			private WhereParameter _TintRoute_W = null;

			public void WhereClauseReset()
			{
				_DId_W = null;
				_TintOrder_W = null;
				_TintRoute_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private EasyObject _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter DId
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(RoutingOrderSchema.DId);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter TintOrder
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(RoutingOrderSchema.TintOrder);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter TintRoute
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(RoutingOrderSchema.TintRoute);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter DId
		    {
				get
		        {
					if(_DId_W == null)
	        	    {
						_DId_W = TearOff.DId;
					}
					return _DId_W;
				}
			}

			public AggregateParameter TintOrder
		    {
				get
		        {
					if(_TintOrder_W == null)
	        	    {
						_TintOrder_W = TearOff.TintOrder;
					}
					return _TintOrder_W;
				}
			}

			public AggregateParameter TintRoute
		    {
				get
		        {
					if(_TintRoute_W == null)
	        	    {
						_TintRoute_W = TearOff.TintRoute;
					}
					return _TintRoute_W;
				}
			}

			private AggregateParameter _DId_W = null;
			private AggregateParameter _TintOrder_W = null;
			private AggregateParameter _TintRoute_W = null;

			public void AggregateClauseReset()
			{
				_DId_W = null;
				_TintOrder_W = null;
				_TintRoute_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private EasyObject _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	}
}
