
// Generated by MyGeneration Version # (1.2.0.2)

using System;
using System.Data.SqlClient;

namespace BWA.bigWebDesk.BLL
{
	public class CreationCats : BWA.bigWebDesk.DAL.CreationCats
	{
        public CreationCats(Guid organizationId)
        {
            this.ConnectionString = Micajah.Common.Bll.Providers.OrganizationProvider.GetConnectionString(organizationId);
        }

        public static void AddCategory(Guid organizationId, int deptID,
                                       int loginCompJuncID,
                                       string name)
        {
            try
            {
                CreationCats cat = new CreationCats(organizationId);
                cat.AddNew();
                cat.DId = deptID;
                cat.VchName = name;
                cat.IntCreated = loginCompJuncID;
                cat.DtCreated = DateTime.UtcNow;
                cat.BtInactive = false;
                cat.Save();
            }
            catch (SqlException ex)
            {
                throw new ApplicationException(ex.Message, ex);
            }
            catch (Exception ex)
            {
                throw new ApplicationException(ex.Message, ex);
            }
        }

	}
}
