
// Generated by MyGeneration Version # (1.2.0.2)

using System;
using System.Data;
using System.Data.Common;
using System.Collections.Specialized;
using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace BWA.bigWebDesk.BLL
{
    public class DeploymentLoggerUser : BWA.bigWebDesk.DAL.DeploymentLoggerUser
    {
        public DeploymentLoggerUser(Guid organizationId)
        {
            this.ConnectionString = Micajah.Common.Bll.Providers.OrganizationProvider.GetConnectionString(organizationId);
        }

        public static int AddUser(Guid organizationId, int BWDLoginID,
                                  int DLUserID)
        {
            DeploymentLoggerUser usr = new DeploymentLoggerUser(organizationId);
            usr.AddNew();
            usr.DLUserID = DLUserID;
            usr.LoginID = BWDLoginID;
            usr.Save();
            return usr.ID;
        }

        public static int GetDLUserID(Guid organizationId, int BWDLoginID)
        {
            DeploymentLoggerUser usr = new DeploymentLoggerUser(organizationId);
            usr.Where.LoginID.Value = BWDLoginID;
            usr.Where.LoginID.Operator = WhereParameter.Operand.Equal;
            usr.Query.Load();
            return usr.DefaultView.Table.Rows.Count > 0 ? usr.DLUserID : 0;
        }
    }
}
