// Generated by MyGeneration Version # (1.2.0.2)

using System;

namespace BWA.bigWebDesk.BLL
{
    public class LocationRouteLevels : BWA.bigWebDesk.DAL.LocationRouteLevels
    {
        public LocationRouteLevels(Guid organizationId)
        {
            this.ConnectionString = Micajah.Common.Bll.Providers.OrganizationProvider.GetConnectionString(organizationId);
        }

        public static int AddDefaultRootLevel(Guid organizationId, int departmentID,
                                              int locationID,
                                              int userID)
        {
            LocationRouteLevels rl = new LocationRouteLevels(organizationId);
            rl.AddNew();
            rl.DId = departmentID;
            rl.LocationId = locationID;
            rl.LastResortTechId = userID;
            rl.TechPoolType = 0;
            rl.RoutingMethod = 0;
            rl.TicketLevel = 1;
            rl.Save();
            return rl.Id;
        }
    }
}