
// Generated by MyGeneration Version # (1.2.0.2)

using System;

namespace BWA.bigWebDesk.BLL
{
    public class TktLevels : BWA.bigWebDesk.DAL.TktLevels
    {
        public TktLevels(Guid organizationId)
        {
            this.ConnectionString = Micajah.Common.Bll.Providers.OrganizationProvider.GetConnectionString(organizationId);
        }

        public static void AddDefaultLevel(Guid organizationId, int departmentID,
                                          int userID,
                                          string levelName)
        {
            TktLevels tl = new TktLevels(organizationId);
            tl.AddNew();
            tl.DId = departmentID;
            tl.IntLastResortId = userID;
            tl.TintLevel = 1;
            tl.BitDefault = true;
            tl.s_Description = "";
            tl.TintRoutingType = 0;
            tl.LevelName = levelName;
            tl.Save();    
        }
    }
}